#!/usr/bin/env python3

import argparse
import subprocess
import sys

USAGE = """
git-listall: lists recent commits from some or all branches

Examples:
    git listall
        List the four most recent commits from every branch in the repository

    git listall br1 br2 br3
        List the most recent four commits for branches br1, br2, br3

    git listall -1
    git listall -c 1
    git listall --commit-count=1
        List the most recent commit from every branch in the repository
"""

def _git(*cmd, **kwds):
    out = subprocess.check_output(('git',) + cmd, **kwds)
    lines = out.decode('utf-8').splitlines()
    return (i for i in lines if i.strip())


if '-h' in sys.argv:
    print(USAGE)
    print()

parser = argparse.ArgumentParser()
parser.add_argument(
    '-c',
    '--commit-count',
    default=4,
    help='Number of commits per branch to show',
    type=int,
)
parser.add_argument(
    'branch',
    nargs='*',
    help='Branches to list if non-empty, otherwise list all branches',
)

# Special case to handle -# arguments
argv = []
for i in sys.argv[1:]:
    if i.startswith('-') and i[1:].isnumeric():
        argv.extend(('-c', i[1:]))
    else:
        argv.append(i)

args = parser.parse_args(argv)

if args.branch:
    branches = args.branch
else:
    branches = [b.strip().replace('* ', '') for b in _git('branch')]

cc_flag = '-%d' % args.commit_count
for branch in branches:
    print(branch + ':')
    for commit in _git('log', '--oneline', cc_flag, branch):
        print(' ', commit)
    print()
