#!/usr/bin/env python3
from _gitz import branches
from _gitz import current_branch
from _gitz import git
from _gitz import run_argv

USAGE = """
git-rot: Rotate to the next or previous branch

The rotation is circular.  The order of branches is the same as that in
``git branch``

Examples:
    git rot
        Rotate to the next branch

    git rot 3
        Rotate 3 branches ahead

    git rot -1
    git rot -
        Rotate 1 branch backward
"""


def git_rot(delta='1'):
    delta = -1 if delta == '-' else int(delta)

    brs = branches()
    current = current_branch()
    pos = brs.index(current) + delta
    git('checkout', branches[pos % len(brs)])


if __name__ == '__main__':
    run_argv(USAGE, git_rot)
