#!/usr/bin/env python3
import _gitz

GIT = _gitz.GIT

USAGE = """\
git-rotate: Rotate through all branches

USAGE:
    git rotate [<number-of-positions>]
"""

HELP = """
Change the current branch by rotating through all the branches for this repo
in the order given by the `git branch` command

EXAMPLES:
    git rotate
        Rotate to the next branch

    git rotate 3
        Rotate 3 branches ahead

    git rotate -1
    git rotate -
        Rotate 1 branch backward
"""
PROGRAM = _gitz.Program(USAGE, HELP)


def git_rotate(delta='1'):
    delta = -1 if delta == '-' else int(delta)

    branches = GIT.branches()
    pos = branches.index(GIT.current_branch()) + delta
    GIT.checkout(branches[pos % len(branches)])


if __name__ == '__main__':
    PROGRAM.exit_on_help()
    git_rotate(*PROGRAM.argv)
