#!/usr/bin/env python3
import _gitz
import os

USAGE = """
git-logra: Log recent commits in all branches from multiple repositories

    git logra repo [..repo]

Examples:
    git logra r1 r2
        List the four most recent commits in each branch of r1 and r2

    git logra -1 r1 r2
    git logra -c 1  r1 r2
    git logra --commit-count=1  r1 r2
        List the most recent one commit in each branch from r1 and r2
"""


def add_arguments(parser):
    parser.add_argument('repo', nargs='+', help='Repos to list')


def git_logra(args):
    cc_flag = '-%d' % args.commit_count
    cwd = os.getcwd()
    for repo in args.repo:
        os.chdir(repo)
        try:
            _gitz.cd_git_root()
            print('%s:' % repo)
            for branch in _gitz.branches():
                print('  (%s)' % branch)
                for commit in _gitz.git('log', '--oneline', cc_flag, branch):
                    print('   ', commit)
                print()

        finally:
            os.chdir(cwd)


args = _gitz.commit_count(add_arguments, USAGE)
git_logra(args)
