#!/usr/bin/env python3
import _gitz
import os

USAGE = """
git-logr: Log recent commits from multiple repositories

    git logr repo [..repo]

Examples:
    git logr r1 r2
        List the four most recent commits from r1 and r2

    git logr -1 r1 r2
    git logr -c 1  r1 r2
    git logr --commit-count=1  r1 r2
        List the most recent one commit from r1 and r2
"""


def add_arguments(parser):
    parser.add_argument('repo', nargs='+', help='Repos to list')


def git_logr(args):
    cc_flag = '-%d' % args.commit_count
    cwd = os.getcwd()
    for repo in args.repo:
        os.chdir(repo)
        try:
            _gitz.cd_git_root()
            print('%s: (%s)' % (repo, _gitz.current_branch()))
            for commit in _gitz.git('log', '--oneline', cc_flag):
                print(' ', commit)
            print()

        finally:
            os.chdir(cwd)


args = _gitz.commit_count(add_arguments, USAGE)
git_logr(args)
