#!/usr/bin/env python3
import _gitz

GIT = _gitz.GIT

USAGE = """\
git-rename: Renames a local git branch and one or more remote branches

USAGE:
    git rename [<from-branch>] <to-branch>[:remote :remote...]
"""

HELP = """

Rename the current branch to <to-branch>
"""
PROGRAM = _gitz.GitProgram(USAGE, HELP)


def git_rename(source, target=None):
    PROGRAM.check_help_and_git()

    if not target:
        target = source
        source = _gitz.current_branch()


if __name__ == '__main__':
    git_rename(*PROGRAM.argv)
