#!/usr/bin/env bash

# Originally written by https://www.reddit.com/user/ex1c
# See https://www.reddit.com/r/git/comments/avv34g/nicer_gitstatus/

usage() {
    cat <<EOF

git-st: A compact and elegant git status using color

USAGE:
    git st

EOF
}


while getopts ":h" opt; do
  case $opt in
    h)
      usage
      exit
      ;;
  esac
done

gawk -vOFS='' '
    NR==FNR {
        all[i++] = $0;
        difffiles[$1] = $0;
        next;
    }
    ! ($2 in difffiles) {
        print; next;
    }
    {
        gsub($2, difffiles[$2]);
        print;
    }
    END {
        if (NR != FNR) {
            # Had diff output
            exit;
        }
        # Had no diff output, just print lines from git status -sb
        for (i in all) {
            print all[i];
        }
    }
' \
    <(git diff --color --stat=$(($(tput cols) - 3)) HEAD | sed '$d; s/^ //')\
    <(git -c color.status=always status -sb)
