#!/usr/bin/env python3
from gitz.git import commit_range
from gitz.git import functions
from gitz.git import root
from gitz.git import guess_origin
from gitz.program import ARGS
from gitz.program import PROGRAM
from gitz.git import GIT

SUMMARY = 'Push a sequence of commit IDs to a remote repository'

HELP = """
Starting with a given commit ID, and moving backwards from there,
push each commit ID to its own disposable branch name.

Useful to bring these commits to the attention of your continuous integration
if it has missed some of your commit IDs because you rebased or pushed a
sequences of commits too fast.
"""

EXAMPLES = """
git stripe
    Pushes HEAD~ into its own branch named _gitz_stripe_0

git stripe 3
    Pushes HEAD~, HEAD~2 and HEAD~3 into their own branches named
    _gitz_stripe_0, _gitz_stripe_1 and _gitz_stripe_2

git stripe --offset=5
git stripe -o5
    Pushes HEAD~, HEAD~2 and HEAD~3 into their own branches named
    _gitz_stripe_5, _gitz_stripe_6 and _gitz_stripe_7

git stripe 2 HEAD~3
git stripe HEAD~3 2
    Pushes HEAD~3 and HEAD~4 into two branches named _gitz_stripe_0
    and  _gitz_stripe_1

git stripe 3 --delete
git stripe 3 -d
    Delete any branches named _gitz_stripe_0, _gitz_stripe_1
    aor _gitz_stripe_2

    git stripe -d does not fail if some or all of the branches
    to be deleted are missing

git stripe --delete-all
git stripe -D
    Delete any remote branches starting with _gitz_stripe_

git stripe --prefix=MINE
git stripe -p MINE
    Pushes HEAD~, HEAD~2 and HEAD~3 into their own branches named
    _MINE_0, _MINE_1, _MINE_2

git stripe 2 --prefix=MINE
git stripe 2 -p=MINE
    Pushes HEAD~ and HEAD~2 into their own branches named _MINE_0
    and _MINE_1

git stripe 2 --prefix=MINE --offset
git stripe 2 -p MINE -o10
    Pushes HEAD~ and HEAD~2 into their own branches named _MINE_10
    and _MINE_11
"""

PREFIX = '_gitz_stripe_'
BAD_BRANCH_CHARS = frozenset('~^: ')
_STRIPE_FMT = '{self.commit_id}~{i_offset}:refs/heads/{branch}'


def git_stripe():
    root.check_git()
    Stripe().stripe()


class Stripe:
    def __init__(self):
        self.remote_branches = functions.remote_branches()

        self.commit_id, self.count = commit_range.commit_range(
            ARGS.commit_id, ARGS.count
        )

        if BAD_BRANCH_CHARS.intersection(ARGS.prefix):
            PROGRAM.exit(_ERROR_BRANCH_NAME, ARGS.prefix)

        self.prefix = ARGS.prefix
        if not self.prefix.startswith('_'):
            self.prefix = '_' + self.prefix
        if not self.prefix.endswith('_'):
            self.prefix += '_'

        self.remotes = list(self._remotes())
        self.indexes = range(ARGS.offset, ARGS.offset + self.count)

    def stripe(self):
        if ARGS.delete:
            if ARGS.delete_all:
                PROGRAM.exit(_ERROR_DELETE)
            self._delete()

        elif ARGS.delete_all:
            self._delete_all()

        else:
            self._stripe()

    def _stripe(self):
        if ARGS.careful:
            branches = {self.prefix + str(i) for i in self.indexes}
            remote_branches = set()
            for remote in self.remotes:
                remote_branches.update(self.remote_branches[remote])

            existing = sorted(branches.intersection(remote_branches))
            if existing:
                PROGRAM.exit('Cannot overwrite existing', *existing)

        for i in self.indexes:
            branch = '%s%d' % (self.prefix, i)
            i_offset = i - ARGS.offset
            refspec = _STRIPE_FMT.format(**locals())
            force = functions.force_flags(not ARGS.careful)

            id = ''
            for remote in self.remotes:
                GIT.push(*(force + [remote, refspec]))
                if not id:
                    striped = '%s/%s' % (remote, branch)
                    id, msg = functions.commit_message(striped)

            PROGRAM.log.message('+ %s@%s: %s' % (striped, id, msg))

    def _remotes(self):
        for remote in ARGS.remotes.split(':'):
            if remote == '^':
                yield guess_origin.guess_origin()
            elif remote == '.' or remote in self.remote_branches:
                yield remote
            else:
                PROGRAM.exit('Unknown remote', remote)

    def _delete(self):
        for i in self.indexes:
            branch = '%s%d' % (self.prefix, i)
            refspec = ':refs/heads/' + branch
            for remote in self.remotes:
                if branch in self.remote_branches[remote]:
                    rbranch = '%s/%s' % (remote, branch)
                    cid, cmsg = functions.commit_message(rbranch)
                    GIT.push(remote, refspec)
                    PROGRAM.message('- %s@%s: %s' % (rbranch, cid, cmsg))

    def _delete_all(self):
        for remote in self.remotes:
            for branch in self.remote_branches[remote]:
                if branch.startswith(self.prefix):
                    rbranch = '%s/%s' % (remote, branch)
                    cid = functions.commit_id(rbranch, True)
                    GIT.push(remote, ':refs/heads/' + branch)
                    PROGRAM.log.message('- %s@%s' % (rbranch, cid))


def add_arguments(parser):
    add = parser.add_argument

    add('count', default='', nargs='?', help=_HELP_COUNT)
    add('commit_id', default='', nargs='?', help=_HELP_COMMIT_ID)

    add('-c', '--careful', action='store_true', help=_HELP_CAREFUL)
    add('-D', '--delete-all', action='store_true', help=_HELP_DELETE_ALL)
    add('-d', '--delete', action='store_true', help=_HELP_DELETE)
    add('-o', '--offset', default=0, type=int, help=_HELP_OFFSET)
    add('-p', '--prefix', default=PREFIX, help=_HELP_PREFIX)
    add('-r', '--remotes', default='^', help=_HELP_REMOTE)


_ERROR_BRANCH_NAME = 'Illegal character in branch name'
_ERROR_DELETE = 'Cannot set both of -d/--delete and -D/--delete-all'

_HELP_CAREFUL = 'Do not force push over existing stripes'
_HELP_COMMIT_ID = 'Branch/commit ID of the first stripe (or HEAD~ if none)'
_HELP_COUNT = 'The number of striped branches to be created: default is 1'
_HELP_DELETE = 'Delete the striped branches for this request'
_HELP_DELETE_ALL = 'Delete all striped branches'
_HELP_PREFIX = 'Base name for stripe branches (%s if none)' % PREFIX
_HELP_OFFSET = 'Offset to start numbering stripes'
_HELP_REMOTE = (
    'One or more remote remotes to push to, separated by colon. '
    '  "." means the local repo, "^" means the upstream repo'
)

if __name__ == '__main__':
    PROGRAM.start()
