#!/usr/bin/env python

from __future__ import print_function
import os
import sys
import subprocess
import traceback

USAGE = """
git-split:

    Split the staging area into individual changes.

    Creates a series of commits - one for each new, modified, renamed or
    deleted file. Great for splitting up a larger commit before rebasing it
    down into smaller commits.

Usage:
    git-split

Tip:

    git reset --soft HEAD~ && git split

will split your most recent commit into individual file changes.

"""


def split():
    def git(*cmd, **kwds):
        return subprocess.check_output(('git',) + cmd, **kwds)

    while not os.path.isdir('.git'):
        parent = os.path.dirname(os.getcwd())
        if parent == os.getcwd():
            raise ValueError('Not in a git directory')
        os.chdir(parent)

    splits = 0
    lines = git('status', '--porcelain')

    try:
        lines = lines.decode()
    except:
        pass

    for line in lines.splitlines():
        mode, filename = line.split(None, 1)

        # Renaming is a special case with two files on a line
        # separated by -> and with mode = '??'
        filenames = filename.split(' -> ')
        try:
            if mode == '??':
                git('add', *filenames)
            git('commit', '-m', '[split] %s' % filenames[0], *filenames)
            splits += 1

        except:
            print('ERROR: couldn\'t commit filename %s.' % filename)
            traceback.print_exc()
            print('ERROR:')

    print('%d commit%s generated' % (splits, '' if splits == 1 else 's'))


if __name__ == '__main__':
    if any(h in sys.argv for h in ('-h', '--help')):
        print(USAGE)
    else:
        split()
