#!/usr/bin/env bash
set -Eeo pipefail

usage() {
    cat <<EOF

git-amp: AMend the last commit message and force-Push

    Intended for fixing a spelling mistake you just made and pushed to
    a private branch.

    For your protection, git amp will fail with a message if there are any
    changes in your workspace which would get accidentally mixed into the
    previous commit.

    git-amp rewrites history.
    Do not use on any production, public or shared branch.

USAGE:
    git amp Your new commit message here
    git amp "It's a commit message! (fix #12?)"
        Commit, amend and push with a new message.
        (You need quotes if the message includes special shell characters like
        #, ', ", *, ?, !)

    git amp
        Bring up an editor for a new message, then amend and push

EOF
}

while getopts ":h" opt; do
  case $opt in
    h)
      usage ; exit ; ;;
  esac
done

if ! git diff-index --quiet HEAD -- ; then
    echo "ERROR: Changes in your workspace would be overwritten."
    exit 1
fi

if [ "$1" == "" ]; then
    git commit --amend
else
    git commit --amend -m "$*"
fi
git push -f
