#!/usr/bin/env python3
# See https://www.reddit.com/r/git/comments/ah1euu

import subprocess
import sys

USAGE = """
git-snip:

    Delete one or more commits by ID from your branch by position (0 being
    the current commit, 1 the one before it), or by commit ID.

    This command rewrites history.

Usage:
    git-snip <id> [<id> ...<id>]

All commits

"""
MAX_LINES = 100


def git(*cmd, **kwds):
    out = subprocess.check_output(('git',) + cmd, **kwds)
    lines = out.decode('utf-8').splitlines()
    return (i for i in lines if i.strip())


def main(args):
    lines = git('log', '--oneline', '--%s' % MAX_LINES)
    ids = [i.split()[0].lower() for i in lines if i.strip()]
    indexes = []

    for a in args:
        try:
            index = ids.index(a.lower()[:7])
        except ValueError:
            if a.isnumeric() and int(a) <= MAX_LINES:
                index = int(a)
            raise
        if index in indexes:
            raise ValueError(
                'Duplicate commit index=%d ID=%s' % (index, ids[index])
            )

    for i in reversed(sorted(indexes)):
        git('rebase', 'HEAD~%d' % i, '--onto', 'HEAD~%d' % (i + 1))


if any(h in sys.argv for h in ('-h', '--help')):
    print(USAGE)
else:
    main(sys.argv[1:])
