#!/usr/bin/env python3

from gitz import program
from gitz.commit_indexer import CommitIndexer
from gitz.git import GIT

USAGE = """\
git-snip: Edit one or more commits out of history

USAGE:
    git-snip <id> [<id> ...]
"""
HELP = """"
Edit one or more commits IDs out of the current branch.

IDs 0, 1, 2, 3... are short for HEAD~0, HEAD~1, HEAD~2, HEAD~3...

This command rewrites history and is only intended for use on private
branches.

"""
PROGRAM = program.Program(USAGE, HELP)


def git_snip(*argv):
    PROGRAM.check_help()
    PROGRAM.check_git()

    indexes = []
    errors = []
    dupes = []
    indexer = CommitIndexer()

    for a in argv:
        try:
            index = indexer.index(a)
            if index in indexes:
                dupes.append(a)
            else:
                indexes.append(index)
        except Exception:
            errors.append(a)

    if errors:
        PROGRAM.error('Not commit IDs:', *errors)
    if dupes:
        PROGRAM.error('Duplicate IDs:', *dupes)
    if errors or dupes:
        PROGRAM.exit()

    for i in reversed(sorted(indexes)):
        'HEAD~%s' % i
        GIT.rebase(('HEAD~%s' % i), '--onto', 'HEAD~%s' % (i + 1))


if __name__ == '__main__':
    git_snip(*PROGRAM.argv)
