#!/usr/bin/env python3
import _gitz

GIT = _gitz.GIT

USAGE = """
git-rotate: Rotate to the next or previous branch

The rotateation is circular.  The order of branches is the same as that in
``git branch``

Examples:
    git rotate
        Rotate to the next branch

    git rotate 3
        Rotate 3 branches ahead

    git rotate -1
    git rotate -
        Rotate 1 branch backward
"""


def git_rotate(delta='1'):
    delta = -1 if delta == '-' else int(delta)

    branches = GIT.branches()
    pos = branches.index(GIT.current_branch()) + delta
    GIT.checkout(branches[pos % len(branches)])


if __name__ == '__main__':
    _gitz.run_argv(USAGE, git_rotate)
