#!/usr/bin/env python3
from gitz import git
from gitz import program
from gitz.env import ENV
from gitz.git import GIT

USAGE = """\
git-delete: Deletes one or more branches locally and on all remotes

USAGE:
    git delete <branch-name> [...<branch-name>]
"""

HELP = """
By default, the branches `master` and `develop` and the remote
`upstream` are protected, which means that they are not allowed
to be delete.

Using the --all/-a flag allows protected branches and remotes
to be deleteded.

It's also possible to change which branches or remotes are protected
by setting the environment variable GITZ_PROTECTED_BRANCHES or
GITZ_PROTECTED_REMOTES to a list separated by colons, or to an empty
string to turn off protection entirely.
"""
PROGRAM = program.Program(USAGE, HELP)

_HELP_FORCE = 'Delete branches that have not been merged to master'
_HELP_ALL = 'Delete all, even protected remotes or branches'


def git_delete():
    args = PROGRAM.parse_args(_add_arguments)
    PROGRAM.require_clean_workspace()

    branch = git.current_branch()
    branches = git.branches()

    remaining_branches = set(branches).difference(args.target)
    if not remaining_branches:
        PROGRAM.error_and_exit('This would delete all the branches')

    remotes = GIT.remote()
    if not args.all:
        protected = set(ENV.protected_branches()).intersect(args.target)
        if protected:
            PROGRAM.error_and_exit('These branches are protected:', *protected)
        pr = ENV.protected_remotes()
        remotes = [r for r in remotes if r not in pr]

    if branch not in branches:
        for b in ENV.reference_branches():
            if b in branches:
                GIT.checkout(b)
                break
        else:
            GIT.checkout(sorted(remaining_branches)[0])

    flag = '-D' if args.force else '-d'
    total_count = 0
    for target in args.target:
        count = 0
        if target in branches:
            GIT.branch(flag, target)
            count += 1
        for remote in remotes:
            if git.exists('%s/%s' % (remote, target)):
                GIT.push(remote, '--delete', target)
                count += 1
        if count:
            total_count += count
        else:
            PROGRAM.error('Did not delete any branches for', target)


def _add_arguments(parser):
    parser.add_argument('target', nargs='+')
    parser.add_argument('-a', '--all', action='store_true', help=_HELP_ALL)
    parser.add_argument('-f', '--force', action='store_true', help=_HELP_FORCE)


if __name__ == '__main__':
    git_delete()
