#!/usr/bin/env python3
from gitz import git_functions
from gitz.env import ENV
from gitz.program import PROGRAM
from gitz.program import safe_git
from gitz.program import git

SUMMARY = 'Create and push one or more fresh branches'

USAGE = 'git fresh <branch-name> [...<branch-name>]'

HELP = """
Creates one or more fresh branches from the main working branch
and pushes them them to your git origin.

"""
EXAMPLES = """
git fresh foo
   Create a new branch foo and push to the origin

git fresh one two three
   Create three new branches
"""

_HELP_BRANCHES = 'Names of branches to create'


def git_fresh():
    git_functions.check_clean_workspace()
    branches = git_functions.branches()

    existing = set(branches).intersection(PROGRAM.args.branches)
    if existing:
        PROGRAM.error('Cannot overwrite:', *existing)

    remotes = safe_git.remote()

    if len(remotes) == 1:
        origin = upstream = remotes[0]
    else:
        origin = ENV.origin()[0]
        if origin not in remotes:
            PROGRAM.error('Unknown origin', origin)

        upstream = next((u for u in ENV.upstream() if u in remotes), None)
        if upstream is None:
            PROGRAM.error('No upstream found')

    if PROGRAM.called.get('error'):
        PROGRAM.exit()

    safe_git.fetch(upstream)
    for branch in PROGRAM.args.branches:
        _run_fresh(branch, branches, origin, upstream)

    PROGRAM.log.message('Created:', ','.join(PROGRAM.args.branches))


def _run_fresh(fresh_branch, branches, origin, upstream):
    if fresh_branch in branches:
        PROGRAM.error('Branch name', fresh_branch, 'already exists')

    for branch in ENV.reference_branches():
        refspec = '%s/%s' % (upstream, branch)
        if git_functions.commit_id(refspec):
            git.checkout('-b', fresh_branch, refspec, quiet=True)
            git.push('-u', origin, fresh_branch, quiet=True)
            PROGRAM.message('Created fresh branch', fresh_branch)
            return

    PROGRAM.exit('No reference branch found')


def add_arguments(parser):
    parser.add_argument('branches', nargs='+', help=_HELP_BRANCHES)


if __name__ == '__main__':
    PROGRAM.start(**globals())
