SUMMARIES = {
    'git-adjust': 'Amend any commit',
    'git-all': 'Perform a command on each of multiple branches or directories',
    'git-amp': 'AMend the last commit message and force-Push, somewhat safely',
    'git-copy': 'Copy a git branch locally and on all remotes',
    'git-delete': 'Delete one or more branches locally and remotely',
    'git-gitz': 'Print information about the gitz environment',
    'git-infer': 'Commit changes with an auto-generated message',
    'git-multi-pick': 'Cherry-pick multiple commits, with an optional squash',
    'git-new': 'Create and push new branches',
    'git-rename': 'Rename a git branch locally and on all remotes',
    'git-rotate': 'Rotate through branches in a Git repository',
    'git-save': 'Save and restore state of the git repository',
    'git-shuffle': 'Reorder and delete commits in the current branch',
    'git-split': 'Split a range of commits into many single-file commits',
    'git-st': 'Colorful, compact git status',
    'git-stripe': 'Push a sequence of commit IDs to a remote repository',
    'git-update': 'Update branches from a reference branch',
    'git-when': 'When did each file change (date, commit, message)?',
}
