.TH GIT-ROT 1 "30 April, 2020" "Gitz 0.9.17" "Gitz Manual"

.SH NAME
git-rot - Rotate through branches in a Git repository

.SH SYNOPSIS
.sp
.nf
.ft C
git rot [-h] [-q] [-v] [-n] [steps]
.ft P
.fi


.SH DESCRIPTION
Move through the branches in a Git repository in the order
given by the \fBgit branch\fP command, wrapping around at the end.

.sp
If N is a number, \fBgit\-rotate N\fP rotates N branches forward,
and \fBgit\-rotate \-N\fP rotates N branches backward.

.sp
\fBgit\-rotate\fP on its own rotates one branch forward, and
\fBgit\-rotate \-\fP rotates one branch backward.

.sp
Useful for quickly browsing each branch in a repository one at a time.

.SH OPTIONS
\fB\-h, \-\-help\fP: show this help message and exit

\fB\-q, \-\-quiet\fP: Suppress all output

\fB\-v, \-\-verbose\fP: Report all messages in great detail

\fB\-n, \-\-no\-run\fP: If set, commands will be printed but not executed


\fBsteps\fP: Number of steps to rotate (positive or negative)


.SH EXAMPLES
.TP
.B \fB git rotate \fP
.TP
.B \fB git rotate 1 \fP
.TP
.B \fB git rotate + \fP
Rotates to the next branch

.sp
.TP
.B \fB git rotate 3 \fP
.TP
.B \fB git rotate +3 \fP
Rotates 3 branches ahead

.sp
.TP
.B \fB git rotate \-1 \fP
.TP
.B \fB git rotate \- \fP
Rotates 1 branch backward

.sp
.TP
.B \fB git rotate \-2 \fP
Rotates 2 branches backward

