.TH GIT-AMP 1 "02 November, 2019" "Gitz 0.9.13" "Gitz Manual"

.SH NAME
git-amp - AMend the last commit message and force-Push, somewhat safely

.SH USAGE
.sp
.nf
.ft C
git amp [commit message here]
.ft P
.fi


.SH DESCRIPTION
AMend the last commit message and force\-Push to its upstream branch.

.sp
If arguments are given, they are used as the commit message,
otherwise an editor is brought up to create edit the previous message.

.sp
If that is successful, uses git push \-\-force\-with\-lease to
rewrite the previous commit immediately.

.sp
git amp rewrites history and should only be used on private branches.

.sp
For your protection, 'git amp' will fail with a message if there are
any changes in your workspace which would get accidentally mixed into
the previous commit.

.SH DANGER
Rewrites history!

.SH EXAMPLES
.TP
.B \fB git amp \fP
Bring up an editor for a new commit message, then amend and push

.sp
.TP
.B \fB git amp Some commit message here \fP
Amend and push with the new message "Some commit message here"

.sp
.TP
.B \fB git amp "Commit message! (fix #127)" \fP
Amend and push with message "Commit message! (fix #127)"
(You need quotes if the message includes special shell
characters like (, ), #, !, etc.)

