.TH GIT-GITZ 1 "30 April, 2020" "Gitz 0.9.17" "Gitz Manual"

.SH NAME
git-gitz - Print information about the gitz git commands

.SH SYNOPSIS
.sp
.nf
.ft C
git gitz [-h] [-q] [-v] [-n] [items [items ...]]
.ft P
.fi


.SH DESCRIPTION
\fBgit gitz\fP lists information about the gitz commands.

.sp
By default it lists everything, or you can select one or more subcommands:

.sp
    commands:
        All the gitz commands

.sp
    defaults:
        Default values: protected branches and remotes

.sp
    executable_directory:
        The path to the gitz executables,

.sp
    home_page:
        The home page of the gitz project

.sp
    library_directory:
        The path to the gitz Python library,

.sp
    python:
        About the version of Python used

.sp
    version:
        The version number of gitz

.SH OPTIONS
\fB\-h, \-\-help\fP: show this help message and exit

\fB\-q, \-\-quiet\fP: Suppress all output

\fB\-v, \-\-verbose\fP: Report all messages in great detail

\fB\-n, \-\-no\-run\fP: If set, commands will be printed but not executed


\fBitems\fP: 


.SH EXAMPLES
.TP
.B \fB git gitz commands \fP
.TP
.B \fB git gitz c \fP
Prints the list of gitz commands

.sp
.TP
.B \fB git gitz \fP
.TP
.B \fB git gitz commands defaults executable_directory home_page library_directory python version \fP
.TP
.B \fB git gitz c d e h l p v \fP
Prints everything:
* All the gitz commands
* Default values: protected branches and remotes
* The path to the gitz executables,
* The home page of the gitz project
* The path to the gitz Python library,
* About the version of Python used
* The version number of gitz

.sp
.TP
.B \fB git gitz version exec \fP
Print just the version number and the git executable directory

