.TH GIT-ST 1 "30 April, 2020" "Gitz 0.9.17" "Gitz Manual"

.SH NAME
git-st - Colorful, compact git status

.SH SYNOPSIS
.sp
.nf
.ft C
git st
.ft P
.fi


.SH DESCRIPTION
One\-line status for each file with lines added and removed.

.sp
This version written by https://github.com/PlatyPew/,
original version by https://www.reddit.com/user/ex1c)

