.TH GIT-STRIPE 1 "30 April, 2020" "Gitz 0.9.17" "Gitz Manual"

.SH NAME
git-stripe - Push a sequence of commit IDs to a remote repository

.SH SYNOPSIS
.sp
.nf
.ft C
git stripe [-h] [-q] [-v] [-c COUNT] [-d] [-l] [-o OFFSET] [-r REMOTES] [-s] [-n]
.ft P
.fi


.SH DESCRIPTION
Starting with a given commit ID, and moving backwards from there,
push each commit ID to its own disposable branch name.

.sp
Useful to bring these commits to the attention of your continuous integration
if it has missed some of your commit IDs because you rebased or pushed a
sequences of commits too fast.

.SH OPTIONS
\fB\-h, \-\-help\fP: show this help message and exit

\fB\-q, \-\-quiet\fP: Suppress all output

\fB\-v, \-\-verbose\fP: Report all messages in great detail

\fB\-c COUNT, \-\-count COUNT\fP: The number of striped branches to be created

\fB\-d, \-\-delete\fP: Delete all striped branches

\fB\-l, \-\-list\fP: List all remote stripes

\fB\-o OFFSET, \-\-offset OFFSET\fP: Offset to start numbering stripes

\fB\-r REMOTES, \-\-remotes REMOTES\fP: One or more remote remotes to push to, separated by colon. "." means the local repo, "^" means the upstream repo

\fB\-s, \-\-safe\fP: Do not push over existing stripes: find an unused range of indices

\fB\-n, \-\-no\-run\fP: If set, commands will be printed but not executed


\fBcommits\fP: Branch/commit IDs to be striped (defaults to HEAD~)


.SH EXAMPLES
.TP
.B \fB git stripe \fP
Pushes HEAD~ into its own branch named _gitz_stripe_0

.sp
.TP
.B \fB git stripe \-\-count=3 \fP
.TP
.B \fB git stripe \-c3 \fP
Pushes HEAD~, HEAD~2 and HEAD~3 into their own branches named
_gitz_stripe_0, _gitz_stripe_1 and _gitz_stripe_2

.sp
.TP
.B \fB git stripe \-\-offset=5 \fP
.TP
.B \fB git stripe \-o5 \fP
Pushes HEAD~, HEAD~2 and HEAD~3 into their own branches named
_gitz_stripe_5, _gitz_stripe_6 and _gitz_stripe_7

.sp
.TP
.B \fB git stripe 2 HEAD~3 \fP
.TP
.B \fB git stripe HEAD~3 2 \fP
Pushes HEAD~3 and HEAD~4 into two branches named _gitz_stripe_0
and  _gitz_stripe_1

.sp
.TP
.B \fB git stripe \-\-delete\-all \fP
.TP
.B \fB git stripe \-D \fP
Delete all stripes

