.TH GIT-NEW 1 "30 April, 2020" "Gitz 0.9.17" "Gitz Manual"

.SH NAME
git-new - Create and push new branches

.SH SYNOPSIS
.sp
.nf
.ft C
git new [-h] [-q] [-v] [-f] [-o ORIGIN] [--protected] [-u] [-r REFERENCE_BRANCH] [-n]
.ft P
.fi


.SH DESCRIPTION
Create new branches from the reference branch and push them with
\-\-set\-upstream.

.sp
\fBgit new\fP does the things you really want to safely get new branches
where you can start working and pushing immediately

.sp
\- Fails leaving the workspace unchanged if there are uncommitted changes

.sp
\- Fails if any branch already exists locally or remotely, unless \-f/\-\-force

.sp
\- Fetches the *reference branch* \- a branch on the upstream or origin repo that
  is the main branch for development \- likely upstream/master or origin/master

.sp
\- Create new branches locally from that reference branch commit ID

.sp
\- Pushes them to the remote origin with \-\-set\-upstream

.sp
gitz can guess what the reference branch and remote origin are, and for
nearly all projects this will be correct, or this can be specified at the
command line, per project, or through environment variables \- see \fBgit gitz\fP
for more details.

.SH OPTIONS
\fB\-h, \-\-help\fP: show this help message and exit

\fB\-q, \-\-quiet\fP: Suppress all output

\fB\-v, \-\-verbose\fP: Report all messages in great detail

\fB\-f, \-\-force\fP: Force push over existing branches

\fB\-o ORIGIN, \-\-origin ORIGIN\fP: Remote origin to push to

\fB\-\-protected\fP: Force push over existing or protected branches

\fB\-u, \-\-use\-head\fP: Use HEAD and not reference branch

\fB\-r REFERENCE_BRANCH, \-\-reference\-branch REFERENCE_BRANCH\fP: Branch to create from, in the form \fBbranch\fP or \fBremote/branch\fP

\fB\-n, \-\-no\-run\fP: If set, commands will be printed but not executed


\fBbranches\fP: Names of branches to create


.SH EXAMPLES
.TP
.B \fB git new foo \fP
Create a new branch foo from the reference branch and push to the origin

.sp
.TP
.B \fB git new foo \-\-origin=remote_1 \fP
.TP
.B \fB git new foo \-o remote_1 \fP
Create a new branch foo from the reference branch and push to remote_1

.sp
.TP
.B \fB git new one two three \-\-reference\-branch=some\-remote/master \fP
.TP
.B \fB git new one two three \-r some\-remote/master \fP
Create three new branches from the remote branch some\-remote/master

