.TH GIT-GO 1 "07 October, 2020" "Gitz 0.11.0" "Gitz Manual"

.SH NAME
git-go - Go to a specific location in the current repo

.SH SYNOPSIS
.sp
.nf
.ft C
git go [-h] [-q] [-v] [-n] [cmd]
.ft P
.fi


.SH DESCRIPTION
* top
* issues
* commits

.SH OPTIONS
\fB\-h, \-\-help\fP: show this help message and exit

\fB\-q, \-\-quiet\fP: Suppress all output

\fB\-v, \-\-verbose\fP: Report all messages in great detail

\fB\-n, \-\-no\-run\fP: If set, commands will be printed but not executed


\fBcmd\fP: Command to execute \- choose from commits directory issues project new_releases releases travis


.SH EXAMPLES

