.TH GIT-GO 1 "07 November, 2020" "Gitz 0.11.2" "Gitz Manual"

.SH NAME
git-go - Open a browser page for the current repo

.SH SYNOPSIS
.sp
.nf
.ft C
git go [-h] [-q] [-v] [-n] [cmd]
.ft P
.fi


.SH DESCRIPTION
Usage:

.sp
  \fBgit go [<location>]\fP

.sp
where <location> is one or more letters from:

.sp
* commits: the list of commits for the current branch (the default)

.sp
* directory: the subdirectory in the current branch

.sp
* issues: the issues page

.sp
* project: the root directory for the project

.sp
* new_releases: a form to create new releases

.sp
* releases: a list of existing releases

.sp
* travis: the Travis page for that repo

.SH OPTIONS
\fB\-h, \-\-help\fP: show this help message and exit

\fB\-q, \-\-quiet\fP: Suppress all output

\fB\-v, \-\-verbose\fP: Report all messages in great detail

\fB\-n, \-\-no\-run\fP: If set, commands will be printed but not executed


\fBcmd\fP: Command to execute \- choose from commits directory issues project new_releases

\fBreleases\fP: travis


.SH EXAMPLES
.TP
.B \fB git go \fP

