.TH GIT-STRIPE 1 "24 December, 2019" "Gitz 0.9.13" "Gitz Manual"

.SH NAME
git-stripe - Push a sequence of commit IDs to a remote repository

.SH SYNOPSIS
.sp
.nf
.ft C
git stripe [-h] [-q] [-v] [-c] [-D] [-d] [-o OFFSET] [-p PREFIX] [-r REMOTES] [-n]
.ft P
.fi


.SH DESCRIPTION
Starting with a given commit ID, and moving backwards from there,
push each commit ID to its own disposable branch name.

.sp
Useful to bring these commits to the attention of your continuous integration
if it has missed some of your commit IDs because you rebased or pushed a
sequences of commits too fast.

.SH OPTIONS
\fB\-h, \-\-help\fP: show this help message and exit

\fB\-q, \-\-quiet\fP: Suppress all output

\fB\-v, \-\-verbose\fP: Report all messages in great detail

\fB\-c, \-\-careful\fP: Do not force push over existing stripes

\fB\-D, \-\-delete\-all\fP: Delete all striped branches

\fB\-d, \-\-delete\fP: Delete the striped branches for this request

\fB\-o OFFSET, \-\-offset OFFSET\fP: Offset to start numbering stripes

\fB\-p PREFIX, \-\-prefix PREFIX\fP: Base name for stripe branches (_gitz_stripe_ if none)

\fB\-r REMOTES, \-\-remotes REMOTES\fP: One or more remote remotes to push to, separated by colon. "." means the local repo, "^" means the upstream repo

\fB\-n, \-\-no\-run\fP: If set, commands will be printed but not executed


\fBcount\fP: The number of striped branches to be created: default is 1

\fBcommit_id\fP: Branch/commit ID of the first stripe (or HEAD~ if none)


.SH EXAMPLES
.TP
.B \fB git stripe \fP
Pushes HEAD~ into its own branch named _gitz_stripe_0

.sp
.TP
.B \fB git stripe 3 \fP
Pushes HEAD~, HEAD~2 and HEAD~3 into their own branches named
_gitz_stripe_0, _gitz_stripe_1 and _gitz_stripe_2

.sp
.TP
.B \fB git stripe \-\-offset=5 \fP
.TP
.B \fB git stripe \-o5 \fP
Pushes HEAD~, HEAD~2 and HEAD~3 into their own branches named
_gitz_stripe_5, _gitz_stripe_6 and _gitz_stripe_7

.sp
.TP
.B \fB git stripe 2 HEAD~3 \fP
.TP
.B \fB git stripe HEAD~3 2 \fP
Pushes HEAD~3 and HEAD~4 into two branches named _gitz_stripe_0
and  _gitz_stripe_1

.sp
.TP
.B \fB git stripe 3 \-\-delete \fP
.TP
.B \fB git stripe 3 \-d \fP
Delete any branches named _gitz_stripe_0, _gitz_stripe_1
aor _gitz_stripe_2

.sp
git stripe \-d does not fail if some or all of the branches
to be deleted are missing

.sp
.TP
.B \fB git stripe \-\-delete\-all \fP
.TP
.B \fB git stripe \-D \fP
Delete any remote branches starting with _gitz_stripe_

.sp
.TP
.B \fB git stripe \-\-prefix=MINE \fP
.TP
.B \fB git stripe \-p MINE \fP
Pushes HEAD~, HEAD~2 and HEAD~3 into their own branches named
_MINE_0, _MINE_1, _MINE_2

.sp
.TP
.B \fB git stripe 2 \-\-prefix=MINE \fP
.TP
.B \fB git stripe 2 \-p=MINE \fP
Pushes HEAD~ and HEAD~2 into their own branches named _MINE_0
and _MINE_1

.sp
.TP
.B \fB git stripe 2 \-\-prefix=MINE \-\-offset \fP
.TP
.B \fB git stripe 2 \-p MINE \-o10 \fP
Pushes HEAD~ and HEAD~2 into their own branches named _MINE_10
and _MINE_11

