.TH GIT-UPDATE 1 "30 April, 2020" "Gitz 0.9.17" "Gitz Manual"

.SH NAME
git-update - Update branches from a reference branch

.SH SYNOPSIS
.sp
.nf
.ft C
git update [-h] [-q] [-v] [-f] [-r REFERENCE_BRANCH] [-n] [branches]
.ft P
.fi


.SH DESCRIPTION
\fBgit update\fP goes to each branch in turn, then tries to update it
the reference branch by pulling with \-\-rebase.

.sp
If the rebase fails with a conflict, then \fBgit update\fP aborts the
rebase and returns that branch to its previous condition.

.sp
If the rebase succeeds, \fBgit update\fP force\-pushes the result.

.SH OPTIONS
\fB\-h, \-\-help\fP: show this help message and exit

\fB\-q, \-\-quiet\fP: Suppress all output

\fB\-v, \-\-verbose\fP: Report all messages in great detail

\fB\-f, \-\-force\fP: Force push over non\-matching remote branches

\fB\-r REFERENCE_BRANCH, \-\-reference\-branch REFERENCE_BRANCH\fP: Branch to create from, in the form \fBbranch\fP or \fBremote/branch\fP

\fB\-n, \-\-no\-run\fP: If set, commands will be printed but not executed


\fBbranches\fP: A list of branches to update \- default is all branches


.SH DANGER
Rewrites history!

.SH EXAMPLES
.TP
.B \fB git update \fP
Updates all branches

.sp
.TP
.B \fB git update foo bar \fP
Only updates branches foo and bar

